export interface MockShort {
  id: string;
  title: string;
  channelName: string;
  channelId: string;
  subscriberCount: number;
  thumbnail: string;
  views: number;
  likes: number;
  comments: number;
  uploadedAt: string;
  duration: number;
  categoryId: string;
  description: string;
  niche: string;
}

export const MOCK_SHORTS: MockShort[] = [
  {
    id: 'mock_gaming_1',
    title: 'Why PROs never use this weapon in Valorant',
    channelName: 'GamersHub',
    channelId: 'UC123gaming',
    subscriberCount: 45000,
    thumbnail: 'https://picsum.photos/seed/gaming1/640/360',
    views: 250000,
    likes: 12500,
    comments: 890,
    uploadedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    duration: 42,
    categoryId: '20',
    description: 'The truth about this weapon revealed! #valorant #gaming #shorts #viral #esports',
    niche: 'gaming',
  },
  {
    id: 'mock_motivation_1',
    title: 'POV: You finally understand discipline',
    channelName: 'MindsetMastery',
    channelId: 'UC456motivation',
    subscriberCount: 8500,
    thumbnail: 'https://picsum.photos/seed/motivation1/640/360',
    views: 180000,
    likes: 14400,
    comments: 1240,
    uploadedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    duration: 38,
    categoryId: '22',
    description: 'This changed my life forever. #motivation #discipline #success #mindset #shorts',
    niche: 'motivation',
  },
  {
    id: 'mock_sports_1',
    title: '3 mistakes killing your basketball shot',
    channelName: 'CourtKings',
    channelId: 'UC789sports',
    subscriberCount: 125000,
    thumbnail: 'https://picsum.photos/seed/sports1/640/360',
    views: 420000,
    likes: 21000,
    comments: 1680,
    uploadedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    duration: 55,
    categoryId: '17',
    description: 'Stop doing these NOW! #basketball #sports #training #nba #shorts',
    niche: 'sports',
  },
  {
    id: 'mock_drama_1',
    title: 'She exposed him and this happened...',
    channelName: 'TeaSpillDaily',
    channelId: 'UC101drama',
    subscriberCount: 230000,
    thumbnail: 'https://picsum.photos/seed/drama1/640/360',
    views: 580000,
    likes: 23200,
    comments: 3450,
    uploadedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    duration: 59,
    categoryId: '24',
    description: 'You won\'t believe the ending 😱 #drama #tea #exposed #trending #shorts',
    niche: 'drama',
  },
  {
    id: 'mock_finance_1',
    title: 'How I made $10K in passive income',
    channelName: 'WealthBuilders',
    channelId: 'UC202finance',
    subscriberCount: 67000,
    thumbnail: 'https://picsum.photos/seed/finance1/640/360',
    views: 310000,
    likes: 15500,
    comments: 2140,
    uploadedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    duration: 48,
    categoryId: '27',
    description: 'Anyone can do this! #money #passiveincome #investing #finance #shorts',
    niche: 'finance',
  },
  {
    id: 'mock_gaming_2',
    title: '🎮 This Fortnite glitch is INSANE',
    channelName: 'ProGamerTips',
    channelId: 'UC303gaming',
    subscriberCount: 15000,
    thumbnail: 'https://picsum.photos/seed/gaming2/640/360',
    views: 95000,
    likes: 7600,
    comments: 567,
    uploadedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    duration: 34,
    categoryId: '20',
    description: 'Use it before it gets patched! #fortnite #gaming #glitch #shorts',
    niche: 'gaming',
  },
  {
    id: 'mock_motivation_2',
    title: 'Don\'t quit when you\'re tired',
    channelName: 'DailyMotivation',
    channelId: 'UC404motivation',
    subscriberCount: 3200,
    thumbnail: 'https://picsum.photos/seed/motivation2/640/360',
    views: 75000,
    likes: 6000,
    comments: 423,
    uploadedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    duration: 29,
    categoryId: '22',
    description: 'Quit when you\'re done. #motivation #nevergiveup #hustle #shorts',
    niche: 'motivation',
  },
  {
    id: 'mock_education_1',
    title: 'Did you know your brain does THIS while sleeping?',
    channelName: 'ScienceExplained',
    channelId: 'UC505education',
    subscriberCount: 89000,
    thumbnail: 'https://picsum.photos/seed/education1/640/360',
    views: 340000,
    likes: 20400,
    comments: 1890,
    uploadedAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    duration: 51,
    categoryId: '27',
    description: 'Mind-blowing science facts! #science #education #brain #learning #shorts',
    niche: 'education',
  },
  {
    id: 'mock_lifestyle_1',
    title: 'My 5AM morning routine changed everything',
    channelName: 'LifeOptimized',
    channelId: 'UC606lifestyle',
    subscriberCount: 41000,
    thumbnail: 'https://picsum.photos/seed/lifestyle1/640/360',
    views: 190000,
    likes: 11400,
    comments: 890,
    uploadedAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    duration: 44,
    categoryId: '22',
    description: 'Try this for 30 days! #lifestyle #morningroutine #productivity #shorts',
    niche: 'lifestyle',
  },
  {
    id: 'mock_tech_1',
    title: 'iPhone secret feature Apple never told you',
    channelName: 'TechSecrets',
    channelId: 'UC707tech',
    subscriberCount: 156000,
    thumbnail: 'https://picsum.photos/seed/tech1/640/360',
    views: 480000,
    likes: 28800,
    comments: 2340,
    uploadedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    duration: 37,
    categoryId: '28',
    description: 'This will blow your mind! #iphone #apple #tech #technology #shorts',
    niche: 'tech',
  },
  {
    id: 'mock_sports_2',
    title: 'When you finally nail the perfect shot',
    channelName: 'SportsHighlights',
    channelId: 'UC808sports',
    subscriberCount: 78000,
    thumbnail: 'https://picsum.photos/seed/sports2/640/360',
    views: 215000,
    likes: 17200,
    comments: 980,
    uploadedAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    duration: 41,
    categoryId: '17',
    description: 'That feeling though! #sports #basketball #perfect #shorts',
    niche: 'sports',
  },
  {
    id: 'mock_music_1',
    title: '30 seconds of pure acoustic bliss',
    channelName: 'StringsSoul',
    channelId: 'UC909music',
    subscriberCount: 23000,
    thumbnail: 'https://picsum.photos/seed/music1/640/360',
    views: 145000,
    likes: 11600,
    comments: 670,
    uploadedAt: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
    duration: 30,
    categoryId: '10',
    description: 'Original composition 🎵 #music #guitar #acoustic #instrumental #shorts',
    niche: 'music',
  },
  {
    id: 'mock_gaming_3',
    title: 'What happens when pros play on low settings',
    channelName: 'EsportsAnalysis',
    channelId: 'UC010gaming',
    subscriberCount: 210000,
    thumbnail: 'https://picsum.photos/seed/gaming3/640/360',
    views: 520000,
    likes: 31200,
    comments: 2780,
    uploadedAt: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
    duration: 56,
    categoryId: '20',
    description: 'The secret advantage revealed! #gaming #esports #pro #competitive #shorts',
    niche: 'gaming',
  },
  {
    id: 'mock_motivation_3',
    title: '5 rules that made me a millionaire',
    channelName: 'SuccessPath',
    channelId: 'UC011motivation',
    subscriberCount: 12000,
    thumbnail: 'https://picsum.photos/seed/motivation3/640/360',
    views: 280000,
    likes: 16800,
    comments: 1450,
    uploadedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    duration: 47,
    categoryId: '27',
    description: 'Follow these and thank me later! #success #millionaire #money #motivation #shorts',
    niche: 'motivation',
  },
  {
    id: 'mock_drama_2',
    title: 'The breakup nobody saw coming',
    channelName: 'CelebWatch',
    channelId: 'UC012drama',
    subscriberCount: 340000,
    thumbnail: 'https://picsum.photos/seed/drama2/640/360',
    views: 760000,
    likes: 38000,
    comments: 5670,
    uploadedAt: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    duration: 58,
    categoryId: '24',
    description: 'All the details here! #celebrity #breakup #drama #tea #shorts',
    niche: 'drama',
  },
  {
    id: 'mock_education_2',
    title: 'How to learn anything 10x faster',
    channelName: 'LearnSmart',
    channelId: 'UC013education',
    subscriberCount: 54000,
    thumbnail: 'https://picsum.photos/seed/education2/640/360',
    views: 395000,
    likes: 27650,
    comments: 2100,
    uploadedAt: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
    duration: 52,
    categoryId: '27',
    description: 'Science-backed learning techniques! #learning #study #education #productivity #shorts',
    niche: 'education',
  },
  {
    id: 'mock_tech_2',
    title: 'Stop charging your phone like this',
    channelName: 'TechTipsDaily',
    channelId: 'UC014tech',
    subscriberCount: 98000,
    thumbnail: 'https://picsum.photos/seed/tech2/640/360',
    views: 410000,
    likes: 24600,
    comments: 1890,
    uploadedAt: new Date(Date.now() - 13 * 60 * 60 * 1000).toISOString(),
    duration: 39,
    categoryId: '28',
    description: 'You\'re ruining your battery! #tech #smartphone #battery #tips #shorts',
    niche: 'tech',
  },
  {
    id: 'mock_lifestyle_2',
    title: 'That moment you realize you\'re an adult',
    channelName: 'RelateableLife',
    channelId: 'UC015lifestyle',
    subscriberCount: 19000,
    thumbnail: 'https://picsum.photos/seed/lifestyle2/640/360',
    views: 125000,
    likes: 10000,
    comments: 780,
    uploadedAt: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    duration: 33,
    categoryId: '22',
    description: 'Too real 😅 #relatable #adulting #lifestyle #comedy #shorts',
    niche: 'lifestyle',
  },
  {
    id: 'mock_finance_2',
    title: 'Avoid these 3 investing mistakes',
    channelName: 'SmartInvestor',
    channelId: 'UC016finance',
    subscriberCount: 87000,
    thumbnail: 'https://picsum.photos/seed/finance2/640/360',
    views: 270000,
    likes: 16200,
    comments: 1340,
    uploadedAt: new Date(Date.now() - 19 * 60 * 60 * 1000).toISOString(),
    duration: 46,
    categoryId: '27',
    description: 'I lost $50K learning this! #investing #stocks #finance #money #shorts',
    niche: 'finance',
  },
  {
    id: 'mock_sports_3',
    title: 'This gym hack will change your gains',
    channelName: 'FitnessPro',
    channelId: 'UC017sports',
    subscriberCount: 102000,
    thumbnail: 'https://picsum.photos/seed/sports3/640/360',
    views: 365000,
    likes: 21900,
    comments: 1560,
    uploadedAt: new Date(Date.now() - 17 * 60 * 60 * 1000).toISOString(),
    duration: 43,
    categoryId: '17',
    description: 'Try this at the gym tomorrow! #fitness #gym #workout #gains #shorts',
    niche: 'sports',
  },
  {
    id: 'mock_music_2',
    title: '🎹 When the beat drops perfectly',
    channelName: 'BeatMakers',
    channelId: 'UC018music',
    subscriberCount: 45000,
    thumbnail: 'https://picsum.photos/seed/music2/640/360',
    views: 220000,
    likes: 17600,
    comments: 890,
    uploadedAt: new Date(Date.now() - 21 * 60 * 60 * 1000).toISOString(),
    duration: 35,
    categoryId: '10',
    description: 'Pure vibes! #music #beats #producer #edm #shorts',
    niche: 'music',
  },
  {
    id: 'mock_gaming_4',
    title: 'Can you beat Minecraft in 60 seconds?',
    channelName: 'SpeedrunKing',
    channelId: 'UC019gaming',
    subscriberCount: 5600,
    thumbnail: 'https://picsum.photos/seed/gaming4/640/360',
    views: 88000,
    likes: 7040,
    comments: 456,
    uploadedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    duration: 60,
    categoryId: '20',
    description: 'The ultimate speedrun challenge! #minecraft #gaming #speedrun #challenge #shorts',
    niche: 'gaming',
  },
  {
    id: 'mock_education_3',
    title: 'What school never taught you about money',
    channelName: 'FinancialEducation',
    channelId: 'UC020education',
    subscriberCount: 134000,
    thumbnail: 'https://picsum.photos/seed/education3/640/360',
    views: 445000,
    likes: 31150,
    comments: 2670,
    uploadedAt: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
    duration: 54,
    categoryId: '27',
    description: 'Essential financial literacy! #education #money #finance #learning #shorts',
    niche: 'education',
  },
  {
    id: 'mock_tech_3',
    title: 'AI just changed coding forever',
    channelName: 'CodeRevolution',
    channelId: 'UC021tech',
    subscriberCount: 176000,
    thumbnail: 'https://picsum.photos/seed/tech3/640/360',
    views: 590000,
    likes: 35400,
    comments: 3890,
    uploadedAt: new Date(Date.now() - 6.5 * 60 * 60 * 1000).toISOString(),
    duration: 49,
    categoryId: '28',
    description: 'This is the future! #ai #coding #programming #technology #shorts',
    niche: 'tech',
  },
  {
    id: 'mock_lifestyle_3',
    title: 'My $0 budget apartment transformation',
    channelName: 'DIYHome',
    channelId: 'UC022lifestyle',
    subscriberCount: 28000,
    thumbnail: 'https://picsum.photos/seed/lifestyle3/640/360',
    views: 175000,
    likes: 14000,
    comments: 1120,
    uploadedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    duration: 57,
    categoryId: '22',
    description: 'You can do this too! #diy #apartment #homedecor #lifestyle #shorts',
    niche: 'lifestyle',
  },
];
